### ISSUE TITLE
Sound and Screen Dimming

### ISSUE THREAD

**Issue by JCas01** [fewieden/MMM-AlarmClock#10]
Platform (Hardware/OS): Raspberry Pi

MagicMirror version: 2.1.1

Module version: 1.10

Description of the issue:
I would like my Mirror to wake me up in the morning. But I am currently having 2 problems with the Alarm Clock Module

Firstly, The Sound does not play out of my speaker. But Using `omxplayer` in terminal, I do get sound

Secondly, After I dismiss the Alert. The Screen Stays Dim. The only way to get the brightness back is to exit magic mirror and launch it again.

The Module Config is below
```
{
	module: 'MMM-AlarmClock',
	position: 'top_right',
	config: {
		alarms: [
			{time: "7:30", days: [1,2,3,4,5], title: "Good Morning", message: "Time to get up"},
			],
		touch: 'true'
		sound: 'music.mp3'
		}
},
```
Thanks alot
JCas01

**Comment by JCas01** [comment]
Hi Again,

Just did `git pull` and reinstalled the module. The screen issue seems to of fixed itself, Still working on the sound issue

Thanks Alot
JCas01

**Comment by fewieden** [comment]
Is your speaker set as default audio output in the system?

**Comment by JCas01** [comment]
Yes, I have used `sudo raspi-config` To force it out through the headphone jack, and `omxplayer` Is able to play sound.

**Comment by JCas01** [comment]
I fixed it, I changed the default from alarm.mp3 to music.mp3. Through I can only get sound on some speakers, not all. Will keep thead open for more sound problems

**Comment by JCas01** [comment]
I got it Working, Then it stopped working again.

**Comment by JCas01** [comment]
Status update

I got it working, I had to change the default sound in the .js file to `music.mp3`
But now, When ever I try to use the fade in function. It stops working

Any Ideas?

**Comment by fewieden** [comment]
Sorry I will not be able to debug this any soon.
