### ISSUE TITLE
Default configs not changed with entry in config.js & Webstream not playing

### ISSUE THREAD

**Issue by hsukup1** [fewieden/MMM-AlarmClock#12]
Platform (Hardware/OS): RPi3 B/Raspbian Jessie

Node version: ??

MagicMirror version: 2.3.1

Module version: 1.1.0

Description of the issue: module.config entries in MagicMirror/config/config.js file do not override defaults set in MagicMirror/modules/MMM-AlarmClock/MMM-AlarmClock.js file (see screenshots).

Also, webstream plays nothing, when changed to the default in MMM-AlarmClock.js (does not override default if set in config.js).

MagicMirror/modules/MMM-AlarmClock/MMM-AlarmClock.js change of defaults
![image](https://user-images.githubusercontent.com/38578618/39492800-64f0ad74-4d56-11e8-9a3b-dadf3d71b38f.png)
Note: no sound from this webstream, however, changing other defaults updates the format

MagicMirror/config/config.js 
![image](https://user-images.githubusercontent.com/38578618/39492970-dd714344-4d56-11e8-8f85-2492f477e943.png)
Notes: Options time, days, title, message, timer, volume, & touch work as expected. Options sound & format do not overide defaults set in MMM-AlarmClock.js file.

**Comment by fewieden** [comment]
you shouldn't touch the js file and your config should look more like this
```
{
  module: 'MMM-AlarmClock',
  position: 'top_right',
  config: {
    sound: 'blackforest.mp3',
    format: 'dddd, h:mm a',
    timer: 60000,
    volume: 1.0,
    touch: false,
    alarms: [
      {
        time: '15:23',
        days: [1,2,3,4,5],
        title: 'ABC',
        message: ''
      }
    ]
  }
}
```
you should probably have another look in the readme for the config options

**Comment by hsukup1** [comment]
Thanks for the clarification on the config options. Your readme doesn't show enough detail to know that the "time, days, title, and message" options are the only ones that can be nested in an array under the "alarms" option.

Here is my updated configuration:

`{
	module: 'MMM-AlarmClock',
	position: 'top_right',
	config: {
		sound: 'https://tunein.com/radio/Top-Dog-In-Country-1029-s31849/?autoplay=1',
		format: 'dddd, h:mm a',
		timer: 60000,
		volume: 1.0,
		touch: false,
		alarms: [
			{
				time: '13:32',
				days: [6],
				title: 'Party Line',
				message: 'You're listening to Party Line!',
			},
		],
	},
},`

Couple issues: the url works great when you put it directly in a web browser (Chrome or Chromium) to play the radio station...in your module...no sound.

Also, if I want to have other alarms on my MagicMirror, with other sounds, should I just have multiple AlarmClock modules in my config.js file, or is it possible to specify a different sound for each alarm on the same module?

**Comment by fewieden** [comment]
Luckily two days ago someone just did it https://github.com/fewieden/MMM-AlarmClock/pull/14, this allows you to specify the sound per alarm. Checkout the develop branch to test it.

The link you set is not an audio src. I took a closer look at the page and found this as the audio source `http://162.244.81.209:8032/stream` give it a try

**Comment by fewieden** [comment]
It's now on master
