### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by Ybbet** [fewieden/MMM-AlarmClock#16]
Platform (Hardware/OS): Raspberry Pi 3 B

Node version: v10.4.0

MagicMirror version: 2.4.0

Module version: 1.1.0

Description of the issue: I enable the sound output by hdmi but the alarm sound is not working. I can see the alarm on screen. I configure the Fadetimer to 1sec (my sound is 6sec). But, no sound comes out of the speaker. 
Any idea ?

**Comment by fewieden** [comment]
Did you try to play other sounds on your pi, to see if it's a general issue with your setup or this specific module?

**Comment by Ybbet** [comment]
Hi. I think I found the problem… 
I use the text to speech from Google. In my browser, i work pretty well. But with the module, I've got an error (can't get the audio file).
cf. http://translate.google.com/translate_tts?tl=en&client=tw-ob&q=Your%20text%20here
If I download the audio file and use it with "my_file.mp3", it works pretty well too!

**Comment by fewieden** [comment]
If you inspect this page it is a video player, that's probably the issue. Try a different service or the local file.
