### ISSUE TITLE
Button instead of touchscreen

### ISSUE THREAD

**Issue by ryanshuck** [fewieden/MMM-AlarmClock#21]
How do we use this with a button to turn the alarm off? Is it compatible with MMM-Buttons?

**Comment by fewieden** [comment]
I could add a notification handler for `STOP_ALARM`, that stops the alarm.

**Comment by fewieden** [comment]
It is now implemented in the `develop` branch, if you send the notification `STOP_ALARM` with MMM-Buttons it should work. Happy testing.

**Comment by fewieden** [comment]
https://github.com/fewieden/MMM-AlarmClock/pull/22
