### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by cowboysdude** [fewieden/MMM-AlarmClock#24]
Platform (Hardware/OS):
Any
Node version:
Current
MagicMirror version:
ANY
Module version:
Dev
Description of the issue:
Not an issue a suggestion for enhancement.   Why not just make this a clock with an alarm clock?  Makes much more sense.  You could show the time and if there's an alarm show that under the time... Just and idea.

**Comment by fewieden** [comment]
Not sure if it is easy to implement, because the clock is rerendering every second, but when an aalarm fires this would repeat just the first second of the sound for the specified timeframe.

**Comment by cowboysdude** [comment]
Couldn't that b implemented in a different js file and Caledonia by the
clock ?

**Comment by fewieden** [comment]
I'm not sure if I understood zour last message

**Comment by cowboysdude** [comment]
Yeah me either LOL  Was on my phone and error correct is NOT your friend :)  Let me see if I can figure out the code here :)

What I typed or thought I did was:
Couldn't the alarm be implemented in a different file and called by the clock js?  Basically merging two files into one......BUT I see that that is just not practical at all...... seems like too much work for a simple alarm clock!  :)
