### ISSUE TITLE
stop alarm using gesture sensor.

### ISSUE THREAD

**Issue by 8acoustic** [fewieden/MMM-AlarmClock#30]
I'm using GroveGesture Sensor(PAJ7620u2) MMM-GroveGestures
how to stop alarm using that sensor?

**Comment by fewieden** [comment]
Hi @8acoustic , the module listens for the notification `STOP_ALARM` https://github.com/fewieden/MMM-AlarmClock/blob/e4638b655960c411b44d1244cd1a06551dffc1ef/MMM-AlarmClock.js#L184-L188

In your grove gesture config you would need to specify something like 
```js
"ANTICLOCKWISE": {
  notificationExec: {
    notification: "STOP_ALARM",
    payload: null,
  }
},
```
accordingto the docs https://github.com/eouia/MMM-GroveGestures#details-and-default

**Comment by 8acoustic** [comment]
Tysm for the help, The alarm now stop using the gesture but the widget on the screen doesn't disappear when its stopped...
it disappear after 1 min.

**Comment by fewieden** [comment]
@8acoustic sry for the late reply. Are you using the latest version of the module? I had made a lot of changes.
