### ISSUE TITLE
Alarm does not stop when using a unique event

### ISSUE THREAD

**Issue by TitouBilou** [fewieden/MMM-AlarmClock#6]
Hi There,
The module works fine when alarm is set for a daily, weekly, etc... repeat. However, when I set it for a single event it's firing at the right time but does not stop (I do not have a touch screen device, touch parameter set to false).

Here are my settings in the MMM-AlarmClock.js file:
    defaults: {
        sound: 'alarm.mp3',
        touch: false,
        volume: 1.0,
        format: 'D MMM, HH:mm',
        timer: 15 * 1000 // 15 seconds
},

... and in the config.js file:
{
    module: 'MMM-AlarmClock',
    position: 'top_center',
    config: {
        alarms: [
            {time: "18:30", days: ["8 Apr"], title: "Soccer", message: "Get ready for soccer training!"},
        ],
    }
}
 
I have the same problem when I set "format" to 'DD:MM, HH:mm' and "time" and "days" to time: "18:30", days: [08:04],...

I hope this helps,
Best regards,
Eric.

**Comment by fewieden** [comment]
Hi Eric there is no single event support implemented

**Comment by TitouBilou** [comment]
Hi,

That explains it then! Anything planned regarding this topic?
Thanks for your answer.
regards,
Eric.

**Comment by fewieden** [comment]
No, but feel free to add it yourself and create a pull request for it :)

**Comment by TitouBilou** [comment]
Unfortunately, I'm not good enough to do so...

Thanks anyway,
Regards,
Eric.

2017-04-09 13:35 GMT+02:00 fewieden <notifications@github.com>:
