### ISSUE TITLE
the alarm won't stop!

### ISSUE THREAD

**Issue by emnabarred** [fewieden/MMM-AlarmClock#8]
when the time reaches the alarm time, it wont start!
i've noticed something that the time of the alarm is written in AM but my raspberry pi and MagicMirror is in 24h format.. maybe this has to do with why it isn't working.. but i don't know how to fix it! please help

**Comment by fewieden** [comment]
- The time has to be defined in 24h format.
- The displaying format can be customized with these options http://momentjs.com/docs/#/displaying/format/ for example `format: 'ddd, HH:mm'` would give 24h format.
